
import React from 'react';
import  '../../../public/styles/static-pages/PrivacyPolicy.scss';
import PrivacyPolicies from '../../components/PrivacyPolicy/privpol';


export class PrivacyPolicy extends React.Component {
  constructor(props) {
    super(props);}

  render() {
    return (
      <>
      <PrivacyPolicies/>
      {/* <div className='privacyPolicy'>
  <div className='container'>
    <h3 className='topheading'>Privacy Policy</h3>
    <p className='paragraph'>Privacy Policy Godrej & Boyce Mfg. Ltd. respect your privacy and is committed to protecting it through Company’s compliance with this privacy policy. This policy describes: The types of information that Company may collect from you when you access or use of RMC mobile applications, websites and other online platforms (collectively, 'Platforms'); and Company’s practices for collecting, using, maintaining, protecting and disclosing that information.</p>
    <h4 className='SubHeading'>note:</h4>
    <p className='paragraph'>By visiting this Platform, you agree to be bound by the terms and conditions of this Privacy Policy. If you do not agree please do not use or access the Platforms. This Privacy Policy is incorporated into and subject to the Terms of Service. This policy DOES NOT apply to information that you provide to, or that is collected by, any third-party, such as merchants from which you purchase and/or pay and social networks that you use in connection with Company’s services. Company encourages you to consult directly with such third-parties about their privacy practices. Information which are collected by us. Company collects this information: (Information Collected By the Company) Company collects this information directly or indirectly from you when you provide it to us; and/or as you navigate through the Platforms (information collected automatically may include usage details, IP addresses, location and information collected through cookies, web beacons and other tracking technologies via web or mobile). Through third-party sign-in services including but not limited to Facebook, twitter, Instagram and Google Plus. If you use an integrated social media feature on Company’s websites. The third-party social media site will give us certain information about you. This could include yourname, email address and other personal details.</p>
    <h4 className='SubHeading'>Information You Provide to Us</h4>
    <p className='paragraph'>The Information Company collects on or through the Platforms shall include inter alia: Your full name, address, email address, telephone number, date of birth and any proof of your identity and/or address, postal code, profile picture, password and other information you may provide with your account such as your gender, mobile phone number and website and all other information, you may provide us through third-party sign-in services such as Facebook and Google Plus etc.. In such events/ cases, Company fetches and stores whatever information is made available to us by you through these sign-in services; Your preferences including settings such as time zone and language; • Details of credit, debit or other card used by You for transactions; Details of Your visits to Platform, including but not limited to, location data, web logs and other communication data; transaction-related information, such as when you make purchases, respond to any offers, or download or use applications or browsing details, contact or notification information, and other information in your account profile; Your search details such as search terms you have looked up and results you selected; Your browsing details including time, frequency, features used, etc. by you; Communications between you and other users or merchants through the Platforms; participation by you in a survey, poll, sweepstakes, contest or promotion scheme; your request for certain features (e.g., newsletters, updates or other products); your communication with us about employment opportunities posted; Information you enter into our system when using the Platform, such as contact information and project management information. Information collected through cookies.</p>
    <h4 className='SubHeading'>Information received from Third Parties</h4>
    <p className='paragraph'>Company will be collecting, processing and storing your user ID associated with any social media account (such as your Facebook and Google account) that you use to sign into the Platform or connect with or use the Platform. Also, information will be collected about you from third parties such as partners, marketers, third-party websites, and researchers. Information Collected Through Platforms Information may be collected automatically from the computer or devices (including mobile devices) you use to access the Platforms, even if you use the Platforms without registering or logging in and the same shall include inter alia: Your server’s IP address from where the Platform is being accessed, the type of browser (Internet Explorer, Firefox, Opera, Google Chrome etc.), the operating system of Your system and the website you last visited before visiting to Platform, and your computer, Internet connection and mobile device, other browsing information (connection, speed, connection type etc.), device type, device’s unique device identifier, mobile network information and the device’s telephone number; Details of your use of the Platforms, including location data, traffic data, logs and other communication data and the resources that you use and access on or through the Platforms; Company also may access metadata and other information associated with other files stored on your mobile device. This may include, for example, photographs, audio and video clips, personal contacts and address book information; Company may also collect real-time information about the location of your device, as permitted by you; Unique mobile device identifier (e.g. IDFA or other device IDs on Apple devices like the iPhone and iPad), if you’re using the Platforms on a mobile device, Company may use mobile device IDs (the unique identifier assigned to a device by the manufacturer), instead of cookies, to recognize you. Unlike cookies, mobile device IDs cannot be deleted from records. Company may share it with advertising companies and they may use device IDs to track your use of Company’s applications, track the number of advertisements displayed, measure advertising performance and display advertisements that are more relevant to you. Company may also share it with analytics companies which may use mobile device IDs to track your usage of Company’s applications; Other information relating to your activity on the Platforms, such as your search queries, comments, domain names, search results selected, number of clicks, pages viewed and the order of those pages, how long you visited the Platforms, the date and time you used the Platforms, error logs, and other similar information; Your locations details including the latitude, longitude or altitude of your mobile device, GPS location; In case of mobile application users, the online or offline status of your application.</p>
    <h4 className='SubHeading'>Security</h4>
    <p className='paragraph'>Platform uses ordinary industry standard technology designed to help keep your Personal Information safe. The secure server software (SSL) encrypts all information You put in before it is sent to us. Furthermore, all of the customer data we collect is protected against unauthorized access. To prevent unauthorized access, maintain data accuracy, and ensure correct use of information, We will employ commercially reasonable and practicable security practices and procedures and security methods and technologies. We will also ensure on reasonable commercial efforts basis that any agent or third party that we employ complies with the same security standards as us for the protection of your Personal Information. Your information may be transferred to or be maintained on computers, computer systems and computer resources located outside of your state or country where the privacy laws may not be as protective as those where you live. If You are located outside India and choose to provide information to us, please be aware that Platform keeps or transfers information to India and processes it there. Your submission of such information represents your agreement to that transfer.</p>
    <h4 className='SubHeading'>Data protection (This can be reframed by including some points mentioned under Security Section, highlighted in yellow)</h4>
    <p className='paragraph'>Company will be collecting, processing and storing your user ID associated with any social media account (such as your Facebook and Google account) that you use to sign into the Platform or connect with or use the Platform. Also, information will be collected about you from third parties such as partners, marketers, third-party websites, and researchers. Information Collected Through Platforms Information may be collected automatically from the computer or devices (including mobile devices) you use to access the Platforms, even if you use the Platforms without registering or logging in and the same shall include inter alia: Your server’s IP address from where the Platform is being accessed, the type of browser (Internet Explorer, Firefox, Opera, Google Chrome etc.), the operating system of Your system and the website you last visited before visiting to Platform, and your computer, Internet connection and mobile device, other browsing information (connection, speed, connection type etc.), device type, device’s unique device identifier, mobile network information and the device’s telephone number; Details of your use of the Platforms, including location data, traffic data, logs and other communication data and the resources that you use and access on or through the Platforms; Company also may access metadata and other information associated with other files stored on your mobile device. This may include, for example, photographs, audio and video clips, personal contacts and address book information; Company may also collect real-time information about the location of your device, as permitted by you; Unique mobile device identifier (e.g. IDFA or other device IDs on Apple devices like the iPhone and iPad), if you’re using the Platforms on a mobile device, Company may use mobile device IDs (the unique identifier assigned to a device by the manufacturer), instead of cookies, to recognize you. Unlike cookies, mobile device IDs cannot be deleted from records. Company may share it with advertising companies and they may use device IDs to track your use of Company’s applications, track the number of advertisements displayed, measure advertising performance and display advertisements that are more relevant to you. Company may also share it with analytics companies which may use mobile device IDs to track your usage of Company’s applications; Other information relating to your activity on the Platforms, such as your search queries, comments, domain names, search results selected, number of clicks, pages viewed and the order of those pages, how long you visited the Platforms, the date and time you used the Platforms, error logs, and other similar information; Your locations details including the latitude, longitude or altitude of your mobile device, GPS location; In case of mobile application users, the online or offline status of your application.</p>
    <h4 className='SubHeading'>Phishing</h4>
    <p className='paragraph'>Identity theft and the practice currently known as 'phishing' are of great concern to Platform. Safeguarding information to help protect You from identity theft is a top priority. We do not and will not, at any time, request your credit card information or national identification numbers in a non-secure or unsolicited e-mail or telephone communication.</p>
    <h4 className='SubHeading'>Anonymous or De-Identified Data</h4>
    <p className='paragraph'>Company may anonymize and/or de-identify information collected from you through the Platform or via other means, including via the use of third-party web analytic tools as described below. As a result, Company’s use and disclosure of aggregated and/or de-identified information is not restricted by this Privacy Policy, and it may be used and disclosed to others without limitation</p>
    <h4 className='SubHeading'>Use and disclosure of information collected</h4>
    <p className='paragraph'>Usages Information collected from you can be used for various purposes including inter alia: Facilitate your usage of Platform; To Provide you with the products ordered by you To process and respond to your queries/ requests; To inform you regarding changes in Platform; To analyze, conduct internal reviews, surveys and understand Company’s users, improve the content and features of Company’s Platform, process and complete your transactions, and make special offers; To diagnose technical problems and provide support; To send and receive communications, show advertisements, notifications; To prepare reports, review, etc.; To contact you regarding third party goods and services, offers, to understand your preferences, requirements; To permit you to participate in interactive features offered through Company’s Platform; To detect and protect any error, hacking, fraud, commercial and identity checks; and Any other purpose as required in connection with the Platform.</p>
    <h4 className='SubHeading'>Disclosures</h4>
    <p className='paragraph'> Information collected from you may be disclosed to and/ or for various purposes including inter alia: For legal purposes, requirements, to comply with applicable laws; To Company’s affiliates, subsidiaries and related parties; To Company’s vendors, merchants, contractors, service providers and other third-parties and persons who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which Company disclose it to them; Any person for maintaining security, operating Platforms, to enquire or protect from any fraud, hacking; To third-parties to market their products or services to you; For any other purpose in connection with the aforesaid; For enforcing or applying Company’s terms of use and other agreements, including for billing and collection purposes; If the disclosure, in Company’s belief, is necessary or appropriate to protect Company’s rights, property, or safety, customers or others. This will include exchanging information with other companies and organizations for the purposes of fraud protection and credit risk reduction; and To help us serve better. For reasons not described in the policy, Company would notify you about the same before making any disclosure. Information Technology Act This document is an electronic record under Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes under applicable Indian laws. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published and shall be construed in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.godrejinterio.com website.</p>
  </div>
</div> */}
      </>
    );
  }
}

export default PrivacyPolicy;;
