// eslint-disable-next-line no-unused-vars
const productDetail = {
  productData: {
    uniqueID: '12006',
    partNumber: '124647997444436',
    productName: 'Slimline Locker',
    ribbonText: 'Featured',
    imagesAndVideos: {
      productImages: [
        {
          imageSrc:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
          thumbnail:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
        },
        {
          imageSrc:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/study-unit.png',
          thumbnail:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/study-unit.png',
        },
        {
          imageSrc:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/sofa-img.png',
          thumbnail:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/sofa-img.png',
        },
      ],
      productVideos: [
        {
          videoSrc:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/sofa-img.png',
          thumbnail:
            'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/sofa-img.png',
        },
      ],
    },
    defAttributes: [
      {
        identifier: 'PrimaryMaterialSubtype',
        sequence: '9.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'pms1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Artificial Leather',
            uniqueID: '7000000000000004064',
          },
        ],
        usage: 'Defining',
        displayable: true,
        name: 'Primary Material Subtype',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001527',
      },
      {
        identifier: 'PrimaryColor',
        sequence: '11.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'pc2',
            sequence: '2.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Multi',
            uniqueID: '7000000000000004026',
          },
        ],
        usage: 'Defining',
        displayable: true,
        name: 'Primary Color',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001508',
      },
    ],
    offerPrice: '27000',
    actualPrice: '30000',
    shipingCharges: '500',
    discount: '10%',
    promotionData: [
      {
        heading: 'Cashback Offer',
        description:
          'Gets 10% Cashback upto 5000 on Purchases on 999 or more online. For limited period only',
        tcText: 'T&C Apply',
        tcUrl: '',
      },
      {
        heading: 'Coupon Offer',
        description: 'Use coupon DIWALI and get 999 off',
        tcText: 'T&C Apply',
        tcUrl: '',
      },
    ],
    emiData: '999',
    defaultQuantity: '1',
  },
  features: [
    {
      label: 'Durable Pinewood Frame',
      description: '',
      imgSrc: '',
    },
    {
      label: 'Ease of Cleaning',
      description: '',
      imgSrc: '',
    },
    {
      label: 'Optimum Lumba Support',
      description: '',
      imgSrc: '',
    },
    {
      label: 'Superior Aesthetics',
      description: '',
      imgSrc: '',
    },
    {
      label: 'Fine Upholstery',
      description: '',
      imgSrc: '',
    },
  ],
  purchaseGuide: {},
  productDetails: {
    image:
      'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
    values: [
      {
        identifier: 'ModelSeriesName',
        sequence: '1.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'msn1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Comfy',
            uniqueID: '7000000000000004001',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Model Series Name',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001501',
      },
      {
        identifier: 'WarrantySummary',
        sequence: '2.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'WS',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '1 year Godrej Interio warranty.',
            uniqueID: '7000000000000002627',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Warranty Summary',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001525',
      },
      {
        identifier: 'NetWeight',
        sequence: '3.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'nw1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '3.75',
            uniqueID: '7000000000000004107',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Net Weight',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001502',
      },
      {
        identifier: 'GrossWeight',
        sequence: '4.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'gw1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '4.5',
            uniqueID: '7000000000000004088',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Gross Weight',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001503',
      },
      {
        identifier: 'Style',
        sequence: '5.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'style',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Contemporary & Modern',
            uniqueID: '7000000000000004219',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Style',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001513',
      },
      {
        identifier: 'DeliveryCondition',
        sequence: '6.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'dc1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'DIY(Do-It-Yourself)',
            uniqueID: '7000000000000004222',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Delivery Condition',
        facetable: false,
        comparable: false,
        searchable: true,
        uniqueID: '7000000000000001514',
      },
      {
        identifier: 'SalesPackage',
        sequence: '7.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'pack1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '1 Bean Bag',
            uniqueID: '7000000000000004255',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Sales Package',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001504',
      },
      {
        identifier: 'PrimaryMaterial',
        sequence: '8.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'pm1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Cotton',
            uniqueID: '7000000000000004057',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Primary Material',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001526',
      },
      {
        identifier: 'SecondaryMaterial',
        sequence: '10.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'sm1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Expanded Polystyrene Beans',
            uniqueID: '7000000000000004070',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Secondary Material',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001528',
      },
      {
        identifier: 'FinishColor',
        sequence: '12.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'fc3',
            sequence: '3.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'Tan Brown & Chestnut',
            uniqueID: '7000000000000004037',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Finish Color',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000001509',
      },
      {
        identifier: 'Width(cm)',
        sequence: '13.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'width1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '71.1',
            uniqueID: '7000000000000004134',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Width (cm)',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001510',
      },
      {
        identifier: 'Height(cm)',
        sequence: '14.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'ht1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '106.7',
            uniqueID: '7000000000000004161',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Height (cm)',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001511',
      },
      {
        identifier: 'Depth(cm)',
        sequence: '15.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'depth1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: '71.1',
            uniqueID: '7000000000000004185',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Depth (cm)',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001512',
      },
      {
        identifier: 'CareInstructions',
        sequence: '16.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'CI',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value:
              'Wipe with soft thick cloth. Avoid using bleach when washing upholstery. Do not keep hot items directly on a furniture surface; instead use a hot pad or coasters. To protect your furniture from fading, avoid keeping your furniture next to windows and other places where it can be exposed to direct sunlight. Cleaning your furniture items regularly will help you maintain them for a long time.',
            uniqueID: '7000000000000002612',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Care Instructions',
        facetable: false,
        comparable: false,
        searchable: false,
        uniqueID: '7000000000000001515',
      },
      {
        identifier: 'IsFragile',
        sequence: '17.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'if1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'No',
            uniqueID: '7000000000000004226',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Is Fragile',
        facetable: true,
        comparable: false,
        searchable: true,
        uniqueID: '7000000000000001524',
      },
      {
        identifier: 'Size',
        sequence: '18.00000',
        storeDisplay: false,
        values: [
          {
            identifier: 'size1',
            sequence: '1.00000',
            unitOfMeasure: '',
            unitID: '',
            value: 'XL',
            uniqueID: '7000000000000004285',
          },
        ],
        usage: 'Descriptive',
        displayable: true,
        name: 'Size',
        facetable: true,
        comparable: true,
        searchable: true,
        uniqueID: '7000000000000002516',
      },
    ],
  },
  keywords: ['one seater', 'fabric sofa', 'chair', 'foam sofa', 'sectional'],
  similarProducts: {},
};
module.exports = productDetail;
