// eslint-disable-next-line no-unused-vars
const productData = {
  recordSetCount: 1,
  metaData: {
    price: '1',
  },
  resourceId:
    'https://localhost:3738/search/resources/store/10151/productview/SAMPLE_PDP_S?responseFormat=json&catalogId=10051&currency=INR',
  catalogEntryView: [
    {
      hasSingleSKU: false,
      resourceId:
        'https://localhost:3738/search/resources/store/10151/productview/byId/24502',
      uniqueID: '24502',
      partNumber: 'SAMPLE_PDP_S',
      shortDescription: 'Shjort description coloumn',
      keyword: '0',
      catalogEntryTypeCode: 'ItemBean',
      fullImage:
        '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
      parentCatalogEntryID: '24501',
      thumbnail:
        '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
      buyable: 'true',
      storeID: '10051',
      longDescription: 'Long description coloumn',
      name: 'Name coloumn',
      parentCatalogGroupID: ['10001_11501', '10051_12512'],
      price: [
        {
          usage: 'Display',
          description: 'L',
          currency: 'INR',
          value: '',
        },
        {
          usage: 'Offer',
          description: 'I',
          currency: 'INR',
          value: '',
        },
      ],
      attributes: [
        {
          identifier: 'colorSwatch',
          sequence: '1.00000',
          storeDisplay: false,
          values: [
            {
              identifier: 'colorSwatch1',
              sequence: '1.00000',
              unitOfMeasure: '',
              unitID: '',
              image1: 'images/catalog/apparel/women/Swatches/swatch_black.png',
              value: 'Black',
              image1path:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_black.png',
              uniqueID: '7000000000000007001',
            },
          ],
          usage: 'Defining',
          displayable: true,
          name: 'colorSwatch',
          facetable: true,
          comparable: true,
          searchable: true,
          uniqueID: '7000000000000004001',
        },
        {
          identifier: 'materialSwatch',
          sequence: '2.00000',
          storeDisplay: false,
          values: [
            {
              identifier: 'materialSwatch1',
              sequence: '1.00000',
              unitOfMeasure: '',
              unitID: '',
              image1: 'images/catalog/apparel/women/Swatches/swatch_green.png',
              value: 'Green',
              image1path:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_green.png',
              uniqueID: '7000000000000007006',
            },
          ],
          usage: 'Defining',
          displayable: true,
          name: 'materialSwatch',
          facetable: true,
          comparable: true,
          searchable: true,
          uniqueID: '7000000000000004003',
        },
        {
          identifier: 'ribbon',
          sequence: '3.00000',
          storeDisplay: true,
          values: [
            {
              identifier: 'ribbon1',
              sequence: '1.00000',
              unitOfMeasure: '',
              unitID: '',
              value: 'Clearance',
              uniqueID: '7000000000000007501',
            },
          ],
          usage: 'Descriptive',
          displayable: true,
          name: 'ribbon',
          facetable: true,
          comparable: true,
          searchable: true,
          uniqueID: '7000000000000004002',
        },
        {
          identifier: 'percentOff',
          sequence: '4.00000',
          storeDisplay: false,
          values: [
            {
              identifier: 'percentOff1',
              sequence: '1.00000',
              unitOfMeasure: '',
              unitID: '',
              value: '10percent off sale sample text',
              uniqueID: '7000000000000007503',
            },
          ],
          usage: 'Defining',
          displayable: true,
          name: 'percentOff',
          facetable: true,
          comparable: true,
          searchable: true,
          uniqueID: '7000000000000004004',
        },
        {
          identifier: 'productDetails',
          sequence: '5.00000',
          storeDisplay: false,
          values: [
            {
              identifier: 'productDetailsTab1',
              sequence: '1.00000',
              unitOfMeasure: '',
              unitID: '',
              value: 'Specifications:Style:Modern:Capacity:5seaters:so on',
              uniqueID: '7000000000000009501',
            },
            {
              identifier: 'productDetailsTab2',
              sequence: '2.00000',
              unitOfMeasure: '',
              unitID: '',
              value:
                'Packaging:Element1:elementValue:Element2:elementValue:so on',
              uniqueID: '7000000000000009502',
            },
          ],
          usage: 'Descriptive',
          displayable: true,
          name: 'productDetails',
          facetable: true,
          comparable: true,
          searchable: true,
          uniqueID: '7000000000000004005',
        },
      ],
      attachments: [
        {
          image: 'images/attachments/usages/images_icon.jpg',
          identifier:
            'images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
          catentry_id: '24502',
          usage: 'IMAGES',
          name: 'sample asset 2 text',
          shortdesc: 'Sample asset 2 short description',
          attachmentAssetID: 3051,
          mimeType: '',
          longdesc: 'Sample asset 2 long description',
          attachmentAssetPath:
            'images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
        },
      ],
      merchandisingAssociations: [
        {
          buyable: 'true',
          resourceId:
            'https://localhost:3738/search/resources/store/10151/productview/byId/22501',
          thumbnail:
            '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
          sKUs: [
            {
              hasSingleSKU: false,
              resourceId:
                'https://localhost:3738/search/resources/store/10151/productview/byId/22502',
              uniqueID: '22502',
              partNumber: 'SAMPLE_SUMMER_S',
              shortDescription: 'Sample product set by in godrej dev',
              keyword: '0',
              catalogEntryTypeCode: 'ItemBean',
              fullImage:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              thumbnail:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              buyable: 'true',
              storeID: '10051',
              name: 'Sample product set by in godrej dev',
              parentCatalogGroupID: ['10001_11501', '10051_12512'],
              price: [
                {
                  usage: 'Display',
                  description: 'L',
                  currency: 'INR',
                  value: '',
                },
                {
                  usage: 'Offer',
                  description: 'I',
                  currency: 'INR',
                  value: '',
                },
              ],
              attributes: [
                {
                  identifier: 'Color',
                  sequence: '1.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'color1',
                      sequence: '1.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      image1:
                        'images/catalog/apparel/women/Swatches/swatch_black.png',
                      value: 'Black',
                      image1path:
                        '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_black.png',
                      uniqueID: '7000000000000005001',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Color',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000002001',
                },
                {
                  identifier: 'Size',
                  sequence: '2.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'size1',
                      sequence: '1.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      value: 'XL',
                      uniqueID: '7000000000000004285',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Size',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000001516',
                },
              ],
            },
            {
              hasSingleSKU: false,
              resourceId:
                'https://localhost:3738/search/resources/store/10151/productview/byId/22503',
              uniqueID: '22503',
              partNumber: 'SAMPLE_SUMMER_L',
              shortDescription: 'Sample product set by in godrej dev',
              keyword: '0',
              catalogEntryTypeCode: 'ItemBean',
              fullImage:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              thumbnail:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              buyable: 'true',
              storeID: '10051',
              name: 'Sample product set by in godrej dev',
              parentCatalogGroupID: ['10001_11501', '10051_12512'],
              price: [
                {
                  usage: 'Display',
                  description: 'L',
                  currency: 'INR',
                  value: '',
                },
                {
                  usage: 'Offer',
                  description: 'I',
                  currency: 'INR',
                  value: '',
                },
              ],
              attributes: [
                {
                  identifier: 'Color',
                  sequence: '1.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'color2',
                      sequence: '2.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      image1:
                        'images/catalog/apparel/women/Swatches/swatch_pink.png',
                      value: 'Pink',
                      image1path:
                        '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_pink.png',
                      uniqueID: '7000000000000005002',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Color',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000002001',
                },
                {
                  identifier: 'Size',
                  sequence: '2.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'size2',
                      sequence: '2.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      value: 'Double',
                      uniqueID: '7000000000000004286',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Size',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000001516',
                },
              ],
            },
          ],
          quantity: 1,
          associationType: 'X-SELL',
          shortDescription: 'Sample product set by in godrej dev',
          parentCatalogGroupID: ['10001_11501', '10051_12512'],
          storeID: '10051',
          numberOfSKUs: 2,
          hasSingleSKU: false,
          price: [
            {
              usage: 'Display',
              description: 'L',
              currency: 'INR',
              value: '',
            },
            {
              usage: 'Offer',
              description: 'I',
              currency: 'INR',
              value: '',
            },
          ],
          name: 'Sample product set by in godrej dev',
          partNumber: 'SAMPLE_SUMMER',
          attributes: [
            {
              identifier: 'Clearance ribbon',
              sequence: '.00000',
              storeDisplay: true,
              values: [
                {
                  identifier: 'Clearance ribbon value',
                  sequence: '.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  value: 'Clearance ribbon value',
                  uniqueID: '7000000000000006501',
                },
              ],
              usage: 'Descriptive',
              displayable: true,
              name: 'Clearance ribbon',
              facetable: false,
              associatedKeyword: '-',
              comparable: true,
              searchable: false,
              uniqueID: '7000000000000003501',
            },
            {
              identifier: 'Ribbon',
              sequence: '.00000',
              storeDisplay: true,
              values: [],
              usage: 'Defining',
              displayable: true,
              name: 'Ribbon',
              facetable: true,
              associatedKeyword: '-',
              comparable: true,
              searchable: true,
              uniqueID: '7000000000000002502',
            },
            {
              identifier: 'Color',
              sequence: '1.00000',
              storeDisplay: false,
              values: [
                {
                  identifier: 'color1',
                  sequence: '1.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  image1:
                    'images/catalog/apparel/women/Swatches/swatch_black.png',
                  value: 'Black',
                  image1path:
                    '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_black.png',
                  uniqueID: '7000000000000005001',
                },
                {
                  identifier: 'color2',
                  sequence: '2.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  image1:
                    'images/catalog/apparel/women/Swatches/swatch_pink.png',
                  value: 'Pink',
                  image1path:
                    '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_pink.png',
                  uniqueID: '7000000000000005002',
                },
              ],
              usage: 'Defining',
              displayable: true,
              name: 'Color',
              facetable: true,
              associatedKeyword: '-',
              comparable: true,
              searchable: true,
              uniqueID: '7000000000000002001',
            },
            {
              identifier: 'Size',
              sequence: '2.00000',
              storeDisplay: false,
              values: [
                {
                  identifier: 'size1',
                  sequence: '1.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  value: 'XL',
                  uniqueID: '7000000000000004285',
                },
                {
                  identifier: 'size2',
                  sequence: '2.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  value: 'Double',
                  uniqueID: '7000000000000004286',
                },
              ],
              usage: 'Defining',
              displayable: true,
              name: 'Size',
              facetable: true,
              associatedKeyword: '-',
              comparable: true,
              searchable: true,
              uniqueID: '7000000000000001516',
            },
          ],
          catalogEntryTypeCode: 'ProductBean',
          keyword: '0',
          uniqueID: '22501',
        },
        {
          buyable: 'true',
          resourceId:
            'https://localhost:3738/search/resources/store/10151/productview/byId/22501',
          thumbnail:
            '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
          sKUs: [
            {
              hasSingleSKU: false,
              resourceId:
                'https://localhost:3738/search/resources/store/10151/productview/byId/22502',
              uniqueID: '22502',
              partNumber: 'SAMPLE_SUMMER_S',
              shortDescription: 'Sample product set by in godrej dev',
              keyword: '0',
              catalogEntryTypeCode: 'ItemBean',
              fullImage:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              thumbnail:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              buyable: 'true',
              storeID: '10051',
              name: 'Sample product set by in godrej dev',
              parentCatalogGroupID: ['10001_11501', '10051_12512'],
              price: [
                {
                  usage: 'Display',
                  description: 'L',
                  currency: 'INR',
                  value: '',
                },
                {
                  usage: 'Offer',
                  description: 'I',
                  currency: 'INR',
                  value: '',
                },
              ],
              attributes: [
                {
                  identifier: 'Color',
                  sequence: '1.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'color1',
                      sequence: '1.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      image1:
                        'images/catalog/apparel/women/Swatches/swatch_black.png',
                      value: 'Black',
                      image1path:
                        '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_black.png',
                      uniqueID: '7000000000000005001',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Color',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000002001',
                },
                {
                  identifier: 'Size',
                  sequence: '2.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'size1',
                      sequence: '1.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      value: 'XL',
                      uniqueID: '7000000000000004285',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Size',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000001516',
                },
              ],
            },
            {
              hasSingleSKU: false,
              resourceId:
                'https://localhost:3738/search/resources/store/10151/productview/byId/22503',
              uniqueID: '22503',
              partNumber: 'SAMPLE_SUMMER_L',
              shortDescription: 'Sample product set by in godrej dev',
              keyword: '0',
              catalogEntryTypeCode: 'ItemBean',
              fullImage:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              thumbnail:
                '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/wcl000_dresses/646x1000/wcl000_0028_a_blue.jpg',
              buyable: 'true',
              storeID: '10051',
              name: 'Sample product set by in godrej dev',
              parentCatalogGroupID: ['10001_11501', '10051_12512'],
              price: [
                {
                  usage: 'Display',
                  description: 'L',
                  currency: 'INR',
                  value: '',
                },
                {
                  usage: 'Offer',
                  description: 'I',
                  currency: 'INR',
                  value: '',
                },
              ],
              attributes: [
                {
                  identifier: 'Color',
                  sequence: '1.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'color2',
                      sequence: '2.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      image1:
                        'images/catalog/apparel/women/Swatches/swatch_pink.png',
                      value: 'Pink',
                      image1path:
                        '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_pink.png',
                      uniqueID: '7000000000000005002',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Color',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000002001',
                },
                {
                  identifier: 'Size',
                  sequence: '2.00000',
                  storeDisplay: false,
                  values: [
                    {
                      identifier: 'size2',
                      sequence: '2.00000',
                      unitOfMeasure: '',
                      unitID: '',
                      value: 'Double',
                      uniqueID: '7000000000000004286',
                    },
                  ],
                  usage: 'Defining',
                  displayable: true,
                  name: 'Size',
                  facetable: true,
                  comparable: true,
                  searchable: true,
                  uniqueID: '7000000000000001516',
                },
              ],
            },
          ],
          quantity: 1,
          associationType: 'UPSELL',
          shortDescription: 'Sample product set by in godrej dev',
          parentCatalogGroupID: ['10001_11501', '10051_12512'],
          storeID: '10051',
          numberOfSKUs: 2,
          hasSingleSKU: false,
          price: [
            {
              usage: 'Display',
              description: 'L',
              currency: 'INR',
              value: '',
            },
            {
              usage: 'Offer',
              description: 'I',
              currency: 'INR',
              value: '',
            },
          ],
          name: 'Sample product set by in godrej dev',
          partNumber: 'SAMPLE_SUMMER',
          attributes: [
            {
              identifier: 'Clearance ribbon',
              sequence: '.00000',
              storeDisplay: true,
              values: [
                {
                  identifier: 'Clearance ribbon value',
                  sequence: '.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  value: 'Clearance ribbon value',
                  uniqueID: '7000000000000006501',
                },
              ],
              usage: 'Descriptive',
              displayable: true,
              name: 'Clearance ribbon',
              facetable: false,
              associatedKeyword: '-',
              comparable: true,
              searchable: false,
              uniqueID: '7000000000000003501',
            },
            {
              identifier: 'Ribbon',
              sequence: '.00000',
              storeDisplay: true,
              values: [],
              usage: 'Defining',
              displayable: true,
              name: 'Ribbon',
              facetable: true,
              associatedKeyword: '-',
              comparable: true,
              searchable: true,
              uniqueID: '7000000000000002502',
            },
            {
              identifier: 'Color',
              sequence: '1.00000',
              storeDisplay: false,
              values: [
                {
                  identifier: 'color1',
                  sequence: '1.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  image1:
                    'images/catalog/apparel/women/Swatches/swatch_black.png',
                  value: 'Black',
                  image1path:
                    '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_black.png',
                  uniqueID: '7000000000000005001',
                },
                {
                  identifier: 'color2',
                  sequence: '2.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  image1:
                    'images/catalog/apparel/women/Swatches/swatch_pink.png',
                  value: 'Pink',
                  image1path:
                    '/wcsstore/GodrejInterioCAS/images/catalog/apparel/women/Swatches/swatch_pink.png',
                  uniqueID: '7000000000000005002',
                },
              ],
              usage: 'Defining',
              displayable: true,
              name: 'Color',
              facetable: true,
              associatedKeyword: '-',
              comparable: true,
              searchable: true,
              uniqueID: '7000000000000002001',
            },
            {
              identifier: 'Size',
              sequence: '2.00000',
              storeDisplay: false,
              values: [
                {
                  identifier: 'size1',
                  sequence: '1.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  value: 'XL',
                  uniqueID: '7000000000000004285',
                },
                {
                  identifier: 'size2',
                  sequence: '2.00000',
                  unitOfMeasure: '',
                  unitID: '',
                  value: 'Double',
                  uniqueID: '7000000000000004286',
                },
              ],
              usage: 'Defining',
              displayable: true,
              name: 'Size',
              facetable: true,
              associatedKeyword: '-',
              comparable: true,
              searchable: true,
              uniqueID: '7000000000000001516',
            },
          ],
          catalogEntryTypeCode: 'ProductBean',
          keyword: '0',
          uniqueID: '22501',
        },
      ],
    },
  ],
  recordSetStartNumber: 0,
  resourceName: 'productview',
  recordSetTotal: 1,
  recordSetTotalMatches: 1,
  recordSetComplete: 'true',
};
module.exports = productData;
