const testJSON = {
  categoryNavigation: {
    categoryArray: [
      {
        name: 'Rooms',
        uniqueid: '10001',
        isleafnode: 'N',
        url: '',
        seourl: '',
        image: '',
        shortdescription: '',
        subCategoryArray: [
          {
            name: 'Living Room',
            uniqueid: '10002',
            isleafnode: 'Y',
            url: '/clp/10002',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Bedroom',
            uniqueid: '10003',
            isleafnode: 'Y',
            url: '/clp/10003',
            seourl: '',
            image: '',
            shortdescription: '',
          },
        ],
      },
      {
        name: 'Products',
        uniqueid: '10005',
        isleafnode: 'N',
        url: '',
        seourl: '',
        image: '',
        shortdescription: '',
        subCategoryArray: [
          {
            name: 'Sofas',
            uniqueid: '10006',
            isleafnode: 'Y',
            url: '/plp/10006',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Recliners',
            uniqueid: '10007',
            isleafnode: 'Y',
            url: '/plp/10007',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Chairs',
            uniqueid: '10008',
            isleafnode: 'Y',
            url: '/plp/10008',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Stools',
            uniqueid: '10009',
            isleafnode: 'Y',
            url: '/plp/10009',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Dining Set',
            uniqueid: '10010',
            isleafnode: 'Y',
            url: '/plp/10010',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Tables',
            uniqueid: '10011',
            isleafnode: 'Y',
            url: '/plp/10011',
            seourl: '',
            image: '',
            shortdescription: '',
          },
        ],
      },
    ],
  },
  subcategories: [
    {
      categoryIdentifier: 'Sofas',
      categoryName: 'Sofas',
      uniqueID: '11503',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/sofa-img.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 1,
      startPrice: '1000',
    },
    {
      categoryIdentifier: 'Beds',
      categoryName: 'Beds',
      uniqueID: '11512',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 9,
      startPrice: '2000',
    },
    {
      categoryIdentifier: 'Wardrobes',
      categoryName: 'Wardrobes',
      uniqueID: '11558',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/bookshelves.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 6,
      startPrice: '3000',
    },
    {
      categoryIdentifier: 'Tables',
      categoryName: 'Tables',
      uniqueID: '11503',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/study-unit.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 1,
      startPrice: '4000',
    },
    {
      categoryIdentifier: 'Dressers',
      categoryName: 'Dressers',
      uniqueID: '11512',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 9,
      startPrice: '5000',
    },
    {
      categoryIdentifier: 'Lamps',
      categoryName: 'Lamps',
      uniqueID: '11558',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/bookshelves.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 6,
      startPrice: '6000',
    },
  ],
  plp: {
    productList: [
      {
        uniqueID: '10101',
        productName: 'Liva King Bed - Shell Wine Red',
        actualPrice: '1000',
        offerPrice: '500',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-1.png',
        ribbonText: 'Featured',
        emiData: '100',
        promotionData: 'Free Accessories',
        discount: '5%',
        hasSwatches: false,
        inStock: true,
      },
      {
        uniqueID: '10102',
        productName: 'Liva King Bed',
        actualPrice: '2000',
        offerPrice: '1200',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-2.png',
        ribbonText: 'Bestseller',
        emiData: '200',
        promotionData: 'Free Accessories',
        discount: '10%',
        hasSwatches: false,
        inStock: false,
      },
      {
        uniqueID: '10103',
        productName: 'Liva King Bed - White',
        actualPrice: '3000',
        offerPrice: '1111',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-3.png',
        ribbonText: 'Featured',
        emiData: '300',
        promotionData: 'Free Accessories',
        discount: '12%',
        hasSwatches: false,
        inStock: true,
      },
      {
        uniqueID: '10104',
        productName: 'Liva King Bed - Wish Storage',
        actualPrice: '5000',
        offerPrice: '5000',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-1.png',
        ribbonText: 'Bestseller',
        emiData: '400',
        promotionData: 'Free Accessories',
        discount: '13%',
        hasSwatches: false,
        inStock: true,
      },
      {
        uniqueID: '19451',
        productName: 'Hermitage Collection Double-Breasted Pea Coat',
        partNumber: 'MCL009_090101',
        actualPrice: '175.0',
        offerPrice: '175.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19452',
        productName: 'Hermitage Collection Double-Breasted Pea Coat',
        partNumber: 'MCL009_090102',
        actualPrice: '175.0',
        offerPrice: '175.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19453',
        productName: 'Hermitage Collection Double-Breasted Pea Coat',
        partNumber: 'MCL009_090103',
        actualPrice: '175.0',
        offerPrice: '175.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19454',
        productName: 'Hermitage Collection Double-Breasted Pea Coat',
        partNumber: 'MCL009_090104',
        actualPrice: '175.0',
        offerPrice: '175.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19455',
        productName: 'Hermitage Collection Double-Breasted Pea Coat',
        partNumber: 'MCL009_090105',
        actualPrice: '175.0',
        offerPrice: '175.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19456',
        productName: 'Hermitage Collection Double-Breasted Pea Coat',
        partNumber: 'MCL009_090106',
        actualPrice: '175.0',
        offerPrice: '175.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19458',
        productName: 'Luigi Valenti Casual Leather Jacket',
        partNumber: 'MCL009_090401',
        actualPrice: '225.0',
        offerPrice: '205.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19459',
        productName: 'Luigi Valenti Casual Leather Jacket',
        partNumber: 'MCL009_090402',
        actualPrice: '225.0',
        offerPrice: '205.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19460',
        productName: 'Luigi Valenti Casual Leather Jacket',
        partNumber: 'MCL009_090403',
        actualPrice: '225.0',
        offerPrice: '205.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19461',
        productName: 'Luigi Valenti Casual Leather Jacket',
        partNumber: 'MCL009_090404',
        actualPrice: '225.0',
        offerPrice: '205.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19462',
        productName: 'Luigi Valenti Casual Leather Jacket',
        partNumber: 'MCL009_090405',
        actualPrice: '225.0',
        offerPrice: '205.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19463',
        productName: 'Luigi Valenti Casual Leather Jacket',
        partNumber: 'MCL009_090406',
        actualPrice: '225.0',
        offerPrice: '205.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19465',
        productName: 'Gusso Diablo Racing Jacket',
        partNumber: 'MCL009_090501',
        actualPrice: '270.0',
        offerPrice: '255.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
      {
        uniqueID: '19466',
        productName: 'Gusso Diablo Racing Jacket',
        partNumber: 'MCL009_090502',
        actualPrice: '270.0',
        offerPrice: '255.0',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.36:8443/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg',
        ribbonText: '',
        emiData: '',
        inStock: '',
        promotionData: null,
      },
    ],
  },
};
module.exports = testJSON;
