const testJSON = {
  categoryNavigation: {
    categoryArray: [
      {
        name: 'Rooms',
        uniqueid: '10001',
        isleafnode: 'N',
        url: '',
        seourl: '',
        image: '',
        shortdescription: '',
        subCategoryArray: [
          {
            name: 'Living Room',
            uniqueid: '10002',
            isleafnode: 'Y',
            url: '/clp/10002',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Bedroom',
            uniqueid: '10003',
            isleafnode: 'Y',
            url: '/clp/10003',
            seourl: '',
            image: '',
            shortdescription: '',
          },
        ],
      },
      {
        name: 'Products',
        uniqueid: '10005',
        isleafnode: 'N',
        url: '',
        seourl: '',
        image: '',
        shortdescription: '',
        subCategoryArray: [
          {
            name: 'Sofas',
            uniqueid: '10006',
            isleafnode: 'Y',
            url: '/plp/10006',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Recliners',
            uniqueid: '10007',
            isleafnode: 'Y',
            url: '/plp/10007',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Chairs',
            uniqueid: '10008',
            isleafnode: 'Y',
            url: '/plp/10008',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Stools',
            uniqueid: '10009',
            isleafnode: 'Y',
            url: '/plp/10009',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Dining Set',
            uniqueid: '10010',
            isleafnode: 'Y',
            url: '/plp/10010',
            seourl: '',
            image: '',
            shortdescription: '',
          },
          {
            name: 'Tables',
            uniqueid: '10011',
            isleafnode: 'Y',
            url: '/plp/10011',
            seourl: '',
            image: '',
            shortdescription: '',
          },
        ],
      },
    ],
  },
  subcategories: [
    {
      categoryIdentifier: 'Sofas',
      categoryName: 'Sofas',
      uniqueID: '11503',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/sofa-img.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 1,
      startPrice: '1000',
    },
    {
      categoryIdentifier: 'Beds',
      categoryName: 'Beds',
      uniqueID: '11512',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 9,
      startPrice: '2000',
    },
    {
      categoryIdentifier: 'Wardrobes',
      categoryName: 'Wardrobes',
      uniqueID: '11558',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/bookshelves.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 6,
      startPrice: '3000',
    },
    {
      categoryIdentifier: 'Tables',
      categoryName: 'Tables',
      uniqueID: '11503',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/study-unit.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 1,
      startPrice: '4000',
    },
    {
      categoryIdentifier: 'Dressers',
      categoryName: 'Dressers',
      uniqueID: '11512',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/mattresses.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 9,
      startPrice: '5000',
    },
    {
      categoryIdentifier: 'Lamps',
      categoryName: 'Lamps',
      uniqueID: '11558',
      imageSrc:
        'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/bookshelves.png',
      onClickUrl: '',
      shortDescription: '',
      seoUrl: '',
      productCount: 6,
      startPrice: '6000',
    },
  ],
  plp: {
    productList: [
      {
        uniqueID: '10101',
        productName: 'Liva King Bed - Shell Wine Red',
        actualPrice: '1000',
        offerPrice: '500',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-1.png',
        ribbonText: 'Featured',
        emiData: '100',
        promotionData: 'Free Accessories',
        discount: '5%',
        hasSwatches: false,
        inStock: true,
      },
      {
        uniqueID: '10102',
        productName: 'Liva King Bed',
        actualPrice: '2000',
        offerPrice: '1200',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-2.png',
        ribbonText: 'Bestseller',
        emiData: '200',
        promotionData: 'Free Accessories',
        discount: '10%',
        hasSwatches: false,
        inStock: false,
      },
      {
        uniqueID: '10103',
        productName: 'Liva King Bed - White',
        actualPrice: '3000',
        offerPrice: '1111',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-3.png',
        ribbonText: 'Featured',
        emiData: '300',
        promotionData: 'Free Accessories',
        discount: '12%',
        hasSwatches: false,
        inStock: true,
      },
      {
        uniqueID: '10104',
        productName: 'Liva King Bed - Wish Storage',
        actualPrice: '5000',
        offerPrice: '5000',
        onClickUrl: '',
        seoUrl: '',
        imageSrc:
          'https://192.168.0.39:8443/wcsstore/GodrejInterioSAS/images/godrejInterio/product-1.png',
        ribbonText: 'Bestseller',
        emiData: '400',
        promotionData: 'Free Accessories',
        discount: '13%',
        hasSwatches: false,
        inStock: true,
      },
      {
          "uniqueID": "19451",
          "productName": "Hermitage Collection Double-Breasted Pea Coat",
          "partNumber": "MCL009_090101",
          "actualPrice": "175.0",
          "offerPrice": "175.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19452",
          "productName": "Hermitage Collection Double-Breasted Pea Coat",
          "partNumber": "MCL009_090102",
          "actualPrice": "175.0",
          "offerPrice": "175.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19453",
          "productName": "Hermitage Collection Double-Breasted Pea Coat",
          "partNumber": "MCL009_090103",
          "actualPrice": "175.0",
          "offerPrice": "175.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19454",
          "productName": "Hermitage Collection Double-Breasted Pea Coat",
          "partNumber": "MCL009_090104",
          "actualPrice": "175.0",
          "offerPrice": "175.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19455",
          "productName": "Hermitage Collection Double-Breasted Pea Coat",
          "partNumber": "MCL009_090105",
          "actualPrice": "175.0",
          "offerPrice": "175.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19456",
          "productName": "Hermitage Collection Double-Breasted Pea Coat",
          "partNumber": "MCL009_090106",
          "actualPrice": "175.0",
          "offerPrice": "175.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0901.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19458",
          "productName": "Luigi Valenti Casual Leather Jacket",
          "partNumber": "MCL009_090401",
          "actualPrice": "225.0",
          "offerPrice": "205.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19459",
          "productName": "Luigi Valenti Casual Leather Jacket",
          "partNumber": "MCL009_090402",
          "actualPrice": "225.0",
          "offerPrice": "205.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19460",
          "productName": "Luigi Valenti Casual Leather Jacket",
          "partNumber": "MCL009_090403",
          "actualPrice": "225.0",
          "offerPrice": "205.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19461",
          "productName": "Luigi Valenti Casual Leather Jacket",
          "partNumber": "MCL009_090404",
          "actualPrice": "225.0",
          "offerPrice": "205.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19462",
          "productName": "Luigi Valenti Casual Leather Jacket",
          "partNumber": "MCL009_090405",
          "actualPrice": "225.0",
          "offerPrice": "205.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19463",
          "productName": "Luigi Valenti Casual Leather Jacket",
          "partNumber": "MCL009_090406",
          "actualPrice": "225.0",
          "offerPrice": "205.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0904.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19465",
          "productName": "Gusso Diablo Racing Jacket",
          "partNumber": "MCL009_090501",
          "actualPrice": "270.0",
          "offerPrice": "255.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19466",
          "productName": "Gusso Diablo Racing Jacket",
          "partNumber": "MCL009_090502",
          "actualPrice": "270.0",
          "offerPrice": "255.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19467",
          "productName": "Gusso Diablo Racing Jacket",
          "partNumber": "MCL009_090503",
          "actualPrice": "270.0",
          "offerPrice": "255.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19468",
          "productName": "Gusso Diablo Racing Jacket",
          "partNumber": "MCL009_090504",
          "actualPrice": "270.0",
          "offerPrice": "255.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19469",
          "productName": "Gusso Diablo Racing Jacket",
          "partNumber": "MCL009_090505",
          "actualPrice": "270.0",
          "offerPrice": "255.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19470",
          "productName": "Gusso Diablo Racing Jacket",
          "partNumber": "MCL009_090506",
          "actualPrice": "270.0",
          "offerPrice": "255.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0905.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19472",
          "productName": "Albini Black Leather Aviator",
          "partNumber": "MCL009_090601",
          "actualPrice": "335.0",
          "offerPrice": "310.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0906.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19473",
          "productName": "Albini Black Leather Aviator",
          "partNumber": "MCL009_090602",
          "actualPrice": "335.0",
          "offerPrice": "310.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0906.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19474",
          "productName": "Albini Black Leather Aviator",
          "partNumber": "MCL009_090603",
          "actualPrice": "335.0",
          "offerPrice": "310.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0906.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19475",
          "productName": "Albini Black Leather Aviator",
          "partNumber": "MCL009_090604",
          "actualPrice": "335.0",
          "offerPrice": "310.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0906.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19476",
          "productName": "Albini Black Leather Aviator",
          "partNumber": "MCL009_090605",
          "actualPrice": "335.0",
          "offerPrice": "310.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0906.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19477",
          "productName": "Albini Black Leather Aviator",
          "partNumber": "MCL009_090606",
          "actualPrice": "335.0",
          "offerPrice": "310.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0906.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19479",
          "productName": "Versatil Belted Cotton Trench",
          "partNumber": "MCL009_090701",
          "actualPrice": "70.0",
          "offerPrice": "70.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0907.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19480",
          "productName": "Versatil Belted Cotton Trench",
          "partNumber": "MCL009_090702",
          "actualPrice": "70.0",
          "offerPrice": "70.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0907.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19481",
          "productName": "Versatil Belted Cotton Trench",
          "partNumber": "MCL009_090703",
          "actualPrice": "70.0",
          "offerPrice": "70.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0907.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19482",
          "productName": "Versatil Belted Cotton Trench",
          "partNumber": "MCL009_090704",
          "actualPrice": "70.0",
          "offerPrice": "70.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0907.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19483",
          "productName": "Versatil Belted Cotton Trench",
          "partNumber": "MCL009_090705",
          "actualPrice": "70.0",
          "offerPrice": "70.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0907.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19484",
          "productName": "Versatil Belted Cotton Trench",
          "partNumber": "MCL009_090706",
          "actualPrice": "70.0",
          "offerPrice": "70.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0907.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19486",
          "productName": "Versatil Mufasa Pea Coat",
          "partNumber": "MCL009_090801",
          "actualPrice": "169.0",
          "offerPrice": "169.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0908.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19487",
          "productName": "Versatil Mufasa Pea Coat",
          "partNumber": "MCL009_090802",
          "actualPrice": "169.0",
          "offerPrice": "169.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0908.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19488",
          "productName": "Versatil Mufasa Pea Coat",
          "partNumber": "MCL009_090803",
          "actualPrice": "169.0",
          "offerPrice": "169.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0908.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19489",
          "productName": "Versatil Mufasa Pea Coat",
          "partNumber": "MCL009_090804",
          "actualPrice": "169.0",
          "offerPrice": "169.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0908.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19490",
          "productName": "Versatil Mufasa Pea Coat",
          "partNumber": "MCL009_090805",
          "actualPrice": "169.0",
          "offerPrice": "169.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0908.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19491",
          "productName": "Versatil Mufasa Pea Coat",
          "partNumber": "MCL009_090806",
          "actualPrice": "169.0",
          "offerPrice": "169.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0908.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19493",
          "productName": "Hermitage Ribbed Collar Leather Bomber",
          "partNumber": "MCL009_090901",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0909.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19494",
          "productName": "Hermitage Ribbed Collar Leather Bomber",
          "partNumber": "MCL009_090902",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0909.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19495",
          "productName": "Hermitage Ribbed Collar Leather Bomber",
          "partNumber": "MCL009_090903",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0909.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19496",
          "productName": "Hermitage Ribbed Collar Leather Bomber",
          "partNumber": "MCL009_090904",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0909.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19497",
          "productName": "Hermitage Ribbed Collar Leather Bomber",
          "partNumber": "MCL009_090905",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0909.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19498",
          "productName": "Hermitage Ribbed Collar Leather Bomber",
          "partNumber": "MCL009_090906",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0909.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19500",
          "productName": "Luigi Valenti Classic Aviator",
          "partNumber": "MCL009_091001",
          "actualPrice": "290.0",
          "offerPrice": "290.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0910.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19501",
          "productName": "Luigi Valenti Classic Aviator",
          "partNumber": "MCL009_091002",
          "actualPrice": "290.0",
          "offerPrice": "290.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0910.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19502",
          "productName": "Luigi Valenti Classic Aviator",
          "partNumber": "MCL009_091003",
          "actualPrice": "290.0",
          "offerPrice": "290.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0910.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19503",
          "productName": "Luigi Valenti Classic Aviator",
          "partNumber": "MCL009_091004",
          "actualPrice": "290.0",
          "offerPrice": "290.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0910.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19504",
          "productName": "Luigi Valenti Classic Aviator",
          "partNumber": "MCL009_091005",
          "actualPrice": "290.0",
          "offerPrice": "290.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0910.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19505",
          "productName": "Luigi Valenti Classic Aviator",
          "partNumber": "MCL009_091006",
          "actualPrice": "290.0",
          "offerPrice": "290.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0910.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19507",
          "productName": "Gusso Flannel Blazer",
          "partNumber": "MCL009_091301",
          "actualPrice": "260.0",
          "offerPrice": "260.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0913.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19508",
          "productName": "Gusso Flannel Blazer",
          "partNumber": "MCL009_091302",
          "actualPrice": "260.0",
          "offerPrice": "260.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0913.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19509",
          "productName": "Gusso Flannel Blazer",
          "partNumber": "MCL009_091303",
          "actualPrice": "260.0",
          "offerPrice": "260.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0913.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19510",
          "productName": "Gusso Flannel Blazer",
          "partNumber": "MCL009_091304",
          "actualPrice": "260.0",
          "offerPrice": "260.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0913.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19511",
          "productName": "Gusso Flannel Blazer",
          "partNumber": "MCL009_091305",
          "actualPrice": "260.0",
          "offerPrice": "260.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0913.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19512",
          "productName": "Gusso Flannel Blazer",
          "partNumber": "MCL009_091306",
          "actualPrice": "260.0",
          "offerPrice": "260.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0913.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19514",
          "productName": "Albini Urban Dweller Jacket",
          "partNumber": "MCL009_091401",
          "actualPrice": "89.0",
          "offerPrice": "89.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0914.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19515",
          "productName": "Albini Urban Dweller Jacket",
          "partNumber": "MCL009_091402",
          "actualPrice": "89.0",
          "offerPrice": "89.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0914.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19516",
          "productName": "Albini Urban Dweller Jacket",
          "partNumber": "MCL009_091403",
          "actualPrice": "89.0",
          "offerPrice": "89.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0914.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19517",
          "productName": "Albini Urban Dweller Jacket",
          "partNumber": "MCL009_091404",
          "actualPrice": "89.0",
          "offerPrice": "89.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0914.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19518",
          "productName": "Albini Urban Dweller Jacket",
          "partNumber": "MCL009_091405",
          "actualPrice": "89.0",
          "offerPrice": "89.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0914.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19519",
          "productName": "Albini Urban Dweller Jacket",
          "partNumber": "MCL009_091406",
          "actualPrice": "89.0",
          "offerPrice": "89.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0914.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19521",
          "productName": "Versatil Montana Suede Jacket",
          "partNumber": "MCL009_091501",
          "actualPrice": "229.0",
          "offerPrice": "229.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0915.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19522",
          "productName": "Versatil Montana Suede Jacket",
          "partNumber": "MCL009_091502",
          "actualPrice": "229.0",
          "offerPrice": "229.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0915.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19523",
          "productName": "Versatil Montana Suede Jacket",
          "partNumber": "MCL009_091503",
          "actualPrice": "229.0",
          "offerPrice": "229.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0915.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19524",
          "productName": "Versatil Montana Suede Jacket",
          "partNumber": "MCL009_091504",
          "actualPrice": "229.0",
          "offerPrice": "229.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0915.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19525",
          "productName": "Versatil Montana Suede Jacket",
          "partNumber": "MCL009_091505",
          "actualPrice": "229.0",
          "offerPrice": "229.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0915.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19526",
          "productName": "Versatil Montana Suede Jacket",
          "partNumber": "MCL009_091506",
          "actualPrice": "229.0",
          "offerPrice": "229.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0915.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19528",
          "productName": "Albini Cashmere Sport Coat",
          "partNumber": "MCL009_091601",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0916.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19529",
          "productName": "Albini Cashmere Sport Coat",
          "partNumber": "MCL009_091602",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0916.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19530",
          "productName": "Albini Cashmere Sport Coat",
          "partNumber": "MCL009_091603",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0916.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19531",
          "productName": "Albini Cashmere Sport Coat",
          "partNumber": "MCL009_091604",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0916.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19532",
          "productName": "Albini Cashmere Sport Coat",
          "partNumber": "MCL009_091605",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0916.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19533",
          "productName": "Albini Cashmere Sport Coat",
          "partNumber": "MCL009_091606",
          "actualPrice": "199.0",
          "offerPrice": "199.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0916.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19535",
          "productName": "Hermitage Porter Coat",
          "partNumber": "MCL009_091701",
          "actualPrice": "97.0",
          "offerPrice": "97.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0917.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19536",
          "productName": "Hermitage Porter Coat",
          "partNumber": "MCL009_091702",
          "actualPrice": "97.0",
          "offerPrice": "97.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0917.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19537",
          "productName": "Hermitage Porter Coat",
          "partNumber": "MCL009_091703",
          "actualPrice": "97.0",
          "offerPrice": "97.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0917.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19538",
          "productName": "Hermitage Porter Coat",
          "partNumber": "MCL009_091704",
          "actualPrice": "97.0",
          "offerPrice": "97.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0917.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19539",
          "productName": "Hermitage Porter Coat",
          "partNumber": "MCL009_091705",
          "actualPrice": "97.0",
          "offerPrice": "97.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0917.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19540",
          "productName": "Hermitage Porter Coat",
          "partNumber": "MCL009_091706",
          "actualPrice": "97.0",
          "offerPrice": "97.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0917.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19542",
          "productName": "Luigi Valenti Black Leather Short Coat",
          "partNumber": "MCL009_091901",
          "actualPrice": "330.0",
          "offerPrice": "315.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0919.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19543",
          "productName": "Luigi Valenti Black Leather Short Coat",
          "partNumber": "MCL009_091902",
          "actualPrice": "330.0",
          "offerPrice": "315.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0919.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19544",
          "productName": "Luigi Valenti Black Leather Short Coat",
          "partNumber": "MCL009_091903",
          "actualPrice": "330.0",
          "offerPrice": "315.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0919.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19545",
          "productName": "Luigi Valenti Black Leather Short Coat",
          "partNumber": "MCL009_091904",
          "actualPrice": "330.0",
          "offerPrice": "315.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0919.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19546",
          "productName": "Luigi Valenti Black Leather Short Coat",
          "partNumber": "MCL009_091905",
          "actualPrice": "330.0",
          "offerPrice": "315.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0919.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19547",
          "productName": "Luigi Valenti Black Leather Short Coat",
          "partNumber": "MCL009_091906",
          "actualPrice": "330.0",
          "offerPrice": "315.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0919.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19549",
          "productName": "Hermitage Tweed Bomber",
          "partNumber": "MCL009_092001",
          "actualPrice": "390.0",
          "offerPrice": "375.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0920.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19550",
          "productName": "Hermitage Tweed Bomber",
          "partNumber": "MCL009_092002",
          "actualPrice": "390.0",
          "offerPrice": "375.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0920.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19551",
          "productName": "Hermitage Tweed Bomber",
          "partNumber": "MCL009_092003",
          "actualPrice": "390.0",
          "offerPrice": "375.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0920.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19552",
          "productName": "Hermitage Tweed Bomber",
          "partNumber": "MCL009_092004",
          "actualPrice": "390.0",
          "offerPrice": "375.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0920.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19553",
          "productName": "Hermitage Tweed Bomber",
          "partNumber": "MCL009_092005",
          "actualPrice": "390.0",
          "offerPrice": "375.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0920.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      },
      {
          "uniqueID": "19554",
          "productName": "Hermitage Tweed Bomber",
          "partNumber": "MCL009_092006",
          "actualPrice": "390.0",
          "offerPrice": "375.0",
          "onClickUrl": "",
          "seoUrl": "",
          "imageSrc": "/wcsstore/SolvedaCommerceCatalogAssetStore//images/catalog/apparel/men/mcl009_jackets/200x310/mcl009_0920.jpg",
          "ribbonText": "",
          "emiData": "",
          "inStock": "",
          "promotionData": null
      }
  ],
  },
};
module.exports = testJSON;
